; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -D ARDUINO_USB_CDC_ON_BOOT
lib_deps = 
	me-no-dev/ESPAsyncWebServer@^3.6.0
	mandulaj/PZEM-004T-v30@^1.1.2
	jgromes/RadioLib@^7.6.0
	bblanchon/ArduinoJson@^7.2.2
	esp32async/AsyncTCP@^3.4.10
	robtillaart/FRAM_I2C@^0.8.4

[env:gateway]
build_flags = -D NODE_GATEWAY
board_build.filesystem = littlefs

[env:node]
build_flags = -D NODE_TELEMETRY

[env:node_nettest]
build_flags =
  -D NODE_TELEMETRY
  -D PZEM_FAKE
